# Generated by Django 2.2.5 on 2019-10-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Name')),
                ('linkage', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Web Address')),
            ],
        ),
    ]
