# Generated by Django 2.2.5 on 2019-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
