# Generated by Django 2.2.5 on 2019-10-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0002_baseuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
